server:
  port: 3001
spring:
  application:
    name: atguigu-crowd-redis
  redis:
    host: 127.0.0.1

#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka